# Generated by Django 5.2 on 2025-04-26 14:51

import demo_test.utils.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=128, null=True, verbose_name="title"),
                ),
                (
                    "photo",
                    models.ImageField(
                        null=True,
                        upload_to=demo_test.utils.utils.get_title_photo_random_filename,
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.CreateModel(
            name="ImageDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="name"
                    ),
                ),
                (
                    "total_count",
                    models.IntegerField(
                        default=0, null=True, verbose_name="Total count"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_details",
                        to="my_app.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "ImageDetails",
                "verbose_name_plural": "ImageDetails",
            },
        ),
    ]
